services:
  mongodb:
    container_name: my_local_mongodb
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
    pull_policy: never  # Ensures the image won't be pulled if it already exists

volumes:
  mongodb_data:
    driver: local